/* pieceNumGenerator generates the piece number for generating a new piece
	inputs:
	Clock is clock
	reset is reset
	outputs:
	pieceNum is the piece number being generated by this generator
	pieceReady says the next piece generation is ready
	cases for piece num:
		0: O piece
		1: I piece
		2: L piece
		3: J piece
		4: Z piece
		5: S piece
		6: T piece
		7: reserved for not valid
*/
module pieceNumGenerator(Clock, reset, pieceRequest, pieceNum, pieceReady);
	input logic Clock, reset, pieceRequest;
	output logic [3:0] pieceNum;
	
	logic [3:0] nextPiece;
	
	
	

	always_ff @(posedge Clock) begin
		if(reset)
			pieceNum <= 4'b1111;
		else 
			pieceNum <= nextPiece;
	end // always_ff @(posedge Clock) begin




endmodule
